import { Poppins } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./provider";
const poppins = Poppins({ weight: ["600"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </SessionWrapper>
  );
}
